article/urls.py
from django.urls import path
from . import views

app_name = "article"

urlpatterns = [
    path("", views.demo, name="demo"),
    path("add_article", views.add_article, name="add_article"),
    path("add_category", views.add_category, name="add_category"),
    path("api_article/", views.ArticleList.as_view()),
    path("apiarticle_category", views.ArticleCategoryList.as_view()),
    path("apiarticle_details/<int:pk>/", views.ArticleDetails.as_view()),
    path("apicategory_details/<int:pk>/", views.ArticleCategoryDetails.as_view()),

]

ecom/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("",include("ecomapp.urls")),
    path("article/",include("article.urls")),
]
if settings.DEBUG:

    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecomapp/urls.py
from django.urls import path
from . import views

app_name = "ecomapp"

urlpatterns = [
    path("", views.list, name="list"),
    path("apiproducts/", views.ProductList.as_view()),
    path("apicategory/", views.CategoryList.as_view()),
    path("apiproduct_details/<int:pk>/", views.ProductDetails.as_view()),
    path("apicategory_details/<int:pk>/", views.CategoryDetails.as_view()),
    path("product/<int:id>/", views.product, name="product"),
    path("category", views.category, name="category"),
    path("p_category/<int:id>/", views.p_category, name="p_category"),
    path("add", views.add_product, name="add_product"),
    path("add_category", views.add_category, name="add_category"),

]

article/models.py
from django.db import models

# Create your models here.
from ecomapp.models import Product


class Article_Category(models.Model):
    name = models.CharField(max_length=150)

    def __str__(self):
        return self.name


class Article(models.Model):
    title = models.CharField(max_length=250)
    content = models.CharField(max_length=500)
    category = models.ForeignKey(Article_Category, on_delete=models.CASCADE, related_name="article_category")
    # product = models.OneToOneField(Product, on_delete=models.CASCADE, related_name="article", null=True, blank=True)
    products = models.ManyToManyField(Product, related_name="articles",blank=True)


    def __str__(self):
        return self.title

ecomapp/models.py
from django.db import models


# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=150)
    description = models.CharField(max_length=500)
    category = models.ForeignKey('Category', on_delete=models.CASCADE, related_name='products')  # Add related_name
    price = models.IntegerField()
    Image = models.ImageField(upload_to="pic")

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=150)

    def __str__(self):
        return self.name

article/forms.py
from django import forms
from .models import Article, Article_Category


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = '__all__'


class ArticleCategory(forms.ModelForm):
    class Meta:
        model = Article_Category
        fields = '__all__'

ecomapp/forms.py
from django import forms
from .models import Product, Category


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'

article/views.py
from django.shortcuts import render, redirect
from rest_framework import generics

from .models import Article, Article_Category
from .serializers import ArticleSerializer, ArticleCategorySerializer
from .forms import ArticleForm, ArticleCategory


# Create your views here.
class ArticleList(generics.ListCreateAPIView):
    queryset = Article.objects.all()
    serializer_class = ArticleSerializer


class ArticleCategoryList(generics.ListCreateAPIView):
    queryset = Article_Category.objects.all()
    serializer_class = ArticleCategorySerializer


class ArticleDetails(generics.RetrieveUpdateDestroyAPIView):
    queryset = Article.objects.all()
    serializer_class = ArticleSerializer


class ArticleCategoryDetails(generics.RetrieveUpdateDestroyAPIView):
    queryset = Article_Category.objects.all()
    serializer_class = ArticleCategorySerializer

def demo(request):
    article = Article.objects.all()
    return render(request, "article.html", {"article": article})


def add_article(request):
    form = ArticleForm(request.POST or None, request.FILES)
    if form.is_valid():
        form.save()
        return redirect('/')
    form = ArticleForm()
    return render(request, "add_article.html", {"form": form})


def add_category(request):
    form = ArticleCategory(request.POST or None, request.FILES)
    if form.is_valid():
        form.save()
        return redirect("article:add_article")
    form = ArticleCategory()
    return render(request, "article_category.html", {'form': form})

ecomapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from rest_framework.parsers import MultiPartParser

from .models import Product, Category
from .forms import ProductForm, CategoryForm
from rest_framework import generics
from .serializers import CustomerSerializer, CategorySerializer


# Create your views here.
def list(request):
    list = Product.objects.all()
    return render(request, "product_list.html", {"list": list})


class ProductList(generics.ListCreateAPIView):
    queryset = Product.objects.all()
    serializer_class = CustomerSerializer


class CategoryList(generics.ListCreateAPIView):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer


class ProductDetails(generics.RetrieveUpdateDestroyAPIView):
    queryset = Product.objects.all()
    serializer_class = CustomerSerializer


class CategoryDetails(generics.RetrieveUpdateDestroyAPIView):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer

def product(request, id):
    pro = Product.objects.get(id=id)
    return render(request, "product.html", {"pro": pro})


def category(request):
    cat = Category.objects.all()
    return render(request, "category.html", {"cat": cat})


def p_category(request, id):
    p_cat = Category.objects.get(id=id)
    category_p = Product.objects.filter(category=p_cat)
    return render(request, "pcategory.html", {"pcat": p_cat, "category": category_p})


def add_product(request):
    form = ProductForm(request.POST or None, request.FILES)
    if form.is_valid():
        form.save()
        return redirect('/')
    form = ProductForm()

    return render(request, 'add_product.html', {'form': form})


def add_category(request):
    form = CategoryForm(request.POST or None, request.FILES)
    if form.is_valid():
        form.save()
        return redirect("ecomapp:add_product")
    form = CategoryForm()
    return render(request, "add_category.html", {'form': form})

ecomapp/templates/Product_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% for list in list %}
<img  src="{{list.Image.url}}" alt="Card image cap"  height="250">
  {{list.name}}
{% endfor %}
</body>
</html>

ecomapp/templates/add_article.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h3>Add Article</h3>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">ADD</button>
</form>
</body>
</html>

ecomapp/templates/add_category.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h3>Add Product Category</h3>
<form method="post" enctype="multipart/form-data">

  {% csrf_token %}
  {{form.as_p}}
  <button type="submit">ADD</button>

</form>
</body>
</html>

ecomapp/templates/add_product.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h3>Add Products</h3>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">ADD</button>

</form>
</body>
</html>

ecomapp/templates/article.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% for article in article %}
{{article.title}}<br>
{{article.content}}<br>
{{article.category}}<br>
{{article.product}}<br>
{#<a href="{% url 'ecomapp:product' article.product.id %}">{{article.product}}</a><br>#}

{% for product in article.products.all %}
  <a href="{% url 'ecomapp:product' product.id %}">{{ product.name }}</a><br>
                    {% endfor %}
{% endfor %}
</body>
</html>

ecomapp/templates/article_category.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h3>Add Article Category</h3>
<form method="post">

  {% csrf_token %}
  {{form.as_p}}
  <button type="submit">ADD</button>

</form>

</body>
</html>

ecomapp/templates/category.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% for i in cat %}
{{i.name}}
{% endfor %}
</body>
</html>

ecomapp/templates/pcategory.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{{pcat.name}}<br>
{% for i in category %}
{{i.name}}<br>
<img src="{{i.Image.url}}"><br>

{{i.description}}<br>
{{i.price}}<br>

{% endfor %}
</body>
</html>

ecomapp/templates/product.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
 {{pro.name}}<br>

<img src="{{pro.Image.url}}"><br>

{{pro.description}}<br>
{{pro.price}}
</body>
</html>